FROM node:20-slim

WORKDIR /app

# Copy package config first to leverage caching
COPY frontend/package*.json ./
RUN npm install

# Copy frontend source files
COPY frontend/ .

EXPOSE 8501

CMD ["npm", "run", "dev"]
